# Generated by Django 5.1.2 on 2024-11-07 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('vacunas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacunaAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('dosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.dosis')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
