# Generated by Django 5.1.2 on 2024-11-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
